### ISSUE TITLE
Transactional AB updates

### ISSUE THREAD

**Issue by gedw99** [gokrazy/autoupdate#1]
I am interested in using gonrazy for a system of iot devices.
For remote updates to work I need transactional updates to be possible.

From what I can see this is not a functionality of gokrazy ?

**Comment by stapelberg** [comment]
What do you mean by transactional updates?

**Comment by gedw99** [comment]
Thanks for the prompt update.

Chrome OS and Ubuntu Core are 2 well known examples.

Important features of it are:
1. The OS pulls down the OS updates in the background whilst the system is working.
2. The system has 2 partitions ( hence the A / B in the name) and will try to apply the update to the other partition and boot of it.
3. If booting of the newly updated fails for whatever reason it will rollback to the old partition. Hence why its called "Transactional".

**Comment by stapelberg** [comment]
This is exactly what gokrazy does. I’ll close this as there is nothing to change here.

**Comment by gedw99** [comment]
thanks. Will give it a try now. I dont have a rasp pi but will run in qemu.
